from .shelterRegisterView import ShelterRegisterView
from .userRegisterView import UserRegisterView
from .loginView import LoginView
from .userUpdateView import UserUpdateView
from .shelterUpdateView import ShelterUpdateView
from .shelterProfileView import ShelterProfileView
from .userProfileView import UserProfileView
from .shelterListView import ShelterListView
from .deleteView import DeleteView
from .shelterGetView import ShelterGetView